### ISSUE TITLE
SMD Blue LEDs no longer available

### ISSUE THREAD

**Issue by ResiduaLiu** [mcubelab/gelslim#1]
Hi,
It seems that the blue LED is obsolete now. I am wondering if there is any replacement for that?

**Comment by themcubelab** [comment]
Yes unfortunately due to COVID supply chain issues it seems the production has stopped. You may be able to use an alternative LED that is a PLCC2 Package Blue LED with a 60 degree vieiwing angle. Here is a [link](https://www.globalsources.com/si/AS/Shenzhen-Best/6008840253093/pdtl/Dome-Blue-LED/1170191189.htm) to one that I found. If you do use this option you will likely need to change the resistance of the blue channel on the pcb.
